server:
  port: 8888

spring:
  application:
    name: zgy-code-generator
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/

# generator default config
generator:
  author: zgy
  outputPath: d://s11/hello
  package:
    module: hello
    parent: com.zgy.learn
  datasource:
    dburl: localhost:3306/myschool
    tables: city,teacher,parents,student,souvenir
