server:
  port: 8888

spring:
  application:
    name: zgy-code-generator

# \u751F\u6210\u7684\u9879\u76EE\u914D\u7F6E
generator:
  author: zgy
  outputPath: d://s11/hello
  package:
    module: hello
    parent: com.zgy.learn
  datasource:
    dburl: localhost:3306/myschool
    tables: city,teacher,parents,student,souvenir
